migration:
	python3 manage.py makemigrations
migrate:
	python3 manage.py migrate
mig:
	make migration && make migrate
run:
	python3 manage.py runserver
i:
	pip install --upgrade pip && pip install -r requirements.txt
cru:
	python manage.py createsuperuser --username goldendev --email goldendevuz@gmail.com
collect:
	python manage.py collectstatic --noinput